### ISSUE TITLE
How to use guide

### ISSUE THREAD

**Issue by LRG-Pasty** [siku2/hass-audioflow#1]
Trying to get this running but a little help me file would help please

**Comment by siku2** [comment]
I will happily accept a PR adding more instructions (or a link to an external guide).

**Comment by siku2** [comment]
@LRG-Pasty, I went ahead and added a more descriptive README as part of some other changes to the integration.
Let me know if you're still having problems with it.

**Comment by LRG-Pasty** [comment]
Ah yes thankyou,
I can now discover device in the network at the discover stage. Device found (3S-4Z) but when i submit a short while after it fails with Connection fail
![Screenshot at 2023-08-28 18-49-24](https://github.com/siku2/hass-audioflow/assets/123261215/2113e52a-64e5-4e80-8393-c3d94ba43c43)
ed.

**Comment by LRG-Pasty** [comment]
Added Via IP and all appears to be running.

**Comment by siku2** [comment]
Never mind, the issue was much sillier than expected. Version 1.0.1 contains the fix (although you probably don't need the auto discovery anymore).

Anyway, thanks for providing feedback and let me know if anything else crops up.

**Comment by LRG-Pasty** [comment]
Sorry couldn't do logs been working away. I have noticed switching between speaker on and off or different speaker selection can be a bit slow catching up from button press to the status change of the icon on screen not sure this a fixable issue. But will to do some testing if you need more info.
Regards Pasty

**Comment by siku2** [comment]
> Sorry couldn't do logs been working away. I have noticed switching between speaker on and off or different speaker selection can be a bit slow catching up from button press to the status change of the icon on screen not sure this a fixable issue. But will to do some testing if you need more info.
> Regards Pasty

Noticed this as well. This is because the device doesn't update its internal state fast enough. When HA asks for a new state after toggling a switch, it still gets the old state from the device and then it takes some time before the state is updated again.

This is fixable though, so let's create a separate issue for it.
